### PR TITLE
remove: dependency for xoutil

### LINKED ISSUE #240: go get failed cause xo/xoutil can't get
## What
- `go get -u github.com/xo/xo` failed because `github.com/xo/xoutil` repository doesn't exist or became private repository.

Output errors
```
$ go get -u github.com/xo/xo
# cd /Users/shogo.tomioka/go/src/github.com/xo/xoutil; git pull --ff-only
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/xo/xoutil: exit status 1
``` 

- it should be changed to remove dependency for `github.com/xo/xoutil` or move repostiroy to under organization.
- I'm not sure I understand the context, but is this repository now a private repository? Is this repository now a private repository or has it been removed from the organization?

### PR DESCRIPTION
**Pull request by tommy-sho**
## What
- fix https://github.com/xo/xo/issues/240
- remove dependency for `xo/xoutil`, instead moved Sqtime under `loader/sqlite.go`
- close #240

### CODE REVIEW

**Comment by kenshaw** [comment]
@tommy-sho appreciate the work here, but I'm in the middle of a top-to-bottom overhaul of `xo`, to get it to work with recent driver changes, and a much better internal architecture that should make maintenance significantly easier moving forward.

**Comment by kenshaw** [comment]
Sorry, in the interim if you need `xoutil` for the old version of `xo` please modify your templates to use this:

```go
// Package xoutil provides additional types for the xo cli tool.
package xoutil

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"reflect"
	"time"

	"github.com/mattn/go-sqlite3"
)

// SqTime provides a type that will correctly scan the various timestamps
// values stored by the github.com/mattn/go-sqlite3 driver for time.Time
// values, as well as correctly satisfying the sql/driver/Valuer interface.
type SqTime struct {
	time.Time
}

// Value satisfies the Valuer interface.
func (t SqTime) Value() (driver.Value, error) {
	return t.Time, nil
}

// Scan satisfies the Scanner interface.
func (t *SqTime) Scan(v interface{}) error {
	switch x := v.(type) {
	case time.Time:
		t.Time = x
		return nil
	case []byte:
		return t.parse(string(x))

	case string:
		return t.parse(x)
	}

	return fmt.Errorf("cannot convert type %s to time.Time", reflect.TypeOf(v))
}

// parse attempts to parse string s to t.
func (t *SqTime) parse(s string) error {
	if s == "" {
		return nil
	}

	for _, f := range sqlite3.SQLiteTimestampFormats {
		z, err := time.Parse(f, s)
		if err == nil {
			t.Time = z
			return nil
		}
	}

	return errors.New("could not parse time")
}
```

**Comment by kenshaw** [comment]
The new version of `xo` will not require this package.

**Comment by tommy-sho** [comment]
thanks for your reply, I'm looking forward to the new version.

**Comment by suntong** [comment]
I'm getting the same problem as well.

> The new version of `xo` will not require this package.

The _"new version"_ means the coming top-to-bottom overhaul of `xo` right?

**Comment by hhhapz** [comment]
Hey @suntong the rewrite has already been completed, approximately since a month ago. Feel free to use XO :). The package is mostly stable now once more and should be working

**Comment by suntong** [comment]
Goya. thx. will try...

**Pull request closed without merging**
