### PR TITLE
Support cross schemas foreign key and multiple schemas generation 

### PR DESCRIPTION
**Pull request by letientai299**
This PR will:

- Replace the `-schema` flag with new `--schemas` flag that can be specified multiple time to generate many schemas at once. User can set `--schemas organizations:org` gen code for schema `organizations` into package `org`.
- Xo will create new folders on the fly instead of forcing users to create them beforehand (because we're now accepting multiple schemas)
- Refactor some code

Current status:

- [x] Postgres
- [x] MySQL
- [x] MS SQL Server
- [x] Oracle
- [x] Update documentation
- [x] Add examples for new features.

Know issues and other notes:

- Code gen for multiple schemas won't work with single file mode since `xo_db.tpl` will be executed multiple times and currently I can't find any good way to solve this properly without refactoring whole project.
- SQLite don't have schema concept, so no need to support

### CODE REVIEW

**Comment by letientai299** [comment]
This will solve #131

**Comment by letientai299** [comment]
@kenshaw what you think about this?

**Comment by letientai299** [comment]
It's been 3 months, can some maintainers give some thought on this PR?

**Comment by ailox** [comment]
I'm no maintainer, but I think this deserves to be bumped a little bit.

I can see some breaking changes here, the API for TypeLoader changed in c1ac78a737671637c6,
"since there's no reason for them to be exported" some methods are no longer exported (LoadProcs, LoadProcParams, LoadRelkind, LoadColumns, LoadForeignKeys, LoadTableForeignKeys, LoadIndexes, LoadTableIndexes, LoadIndexColumns). I wonder if anyone was using those, and if it might be better to stick with the current method names, and move this refactor into a seperate PR?

The CLI command changed for obvious reasons, `schema` flag got deprecated for `schemas`. This will cause trouble in some pipelines for sure, but I can see no way around it. Maybe `schema` could be kept, and emulate the old behavior?

The templates had to change a little, this will cause problems for people that modified and vendored them for their project.

These were the only caveats i could spot.

Changes look clean and are logical, there are tests for table name generation. I started using this branch to play around a bit with multiple schemas and it works like a charm. I would support this to be merged, as it adds multischema support — a crucial feature for existing databases.

Thank you for working on this, letientai299!

**Pull request closed without merging**
