### PR TITLE
merge func_name_none and func_name_context

### PR DESCRIPTION
**Pull request by switchupcb**
The purpose of this PR is to simplify `func.go.tpl` editing for the end user. I'm unsure that I altered the templates correctly. Let me know if I need to remove the `true`/`false` in `{{ func_name true $t }}`.

### CODE REVIEW

**Comment by kenshaw** [comment]
I'm not of the opinion this is simpler/easier to understand. Changing `context` to instead a `true` / `false` parameter is changing out a name for a generic scalar variable that would cause a later developer to remember what the point of that parameter was for.

**Comment by switchupcb** [comment]
> I'm not of the opinion this is simpler/easier to understand. Changing `context` to instead a `true` / `false` parameter is changing out a name for a generic scalar variable that would cause a later developer to remember what the point of that parameter was for.

That's valid in the context of the template where the developer either sees `{{ func_name_none $t }}` or `{{ func_name_context $t }}` (and understands the difference between "none" and "context"). However, in the context of `func.go.tpl`, there are many methods which vary only by the addition of `context`. This results in two functions which contain the same functionality and this can cause confusion.

For example, `func_name_context` returns `nameContext(f.context_both(), <name_var_x>)`, but all `nameContext` does is append "Context" to the name *already provided* in `func_name_none`. Therefore, **duplicate code exists for 2 functions that serve one purpose.**

This pattern (using 2 functions for one purpose) repeats throughout `func.go.tpl` which makes it harder to parse and initially understand. In hindsight, this is the issue I'm addressing with this pull request. As a result, I've committed [`refactor func_name to signify suffix`](https://github.com/xo/xo/pull/314/commits/fc9cb889a529621be6294089ad7d4416fbb4da73) which aims to solve this issue by:
1. Using one function to serve one purpose (of creating the name of the function).
2. Allow a developer to use a name as opposed to a generic scalar during the editing of the actual template.

**Comment by hhhapz** [comment]
While this is true, there is nothing wrong with having duplicate code.

1: The one function will be used for two purposes - creating two different signatures for similar, yes, but not the same function. It's an overload with is unclear.

2: Your new change is still not something I am personally a fan of. You are still passing around magic strings of "Context" and "" in places. I personally am of the opinion that the current codebase is most clear.

**Comment by switchupcb** [comment]
> While this is true, there is nothing wrong with having duplicate code.

When you batch (SQL) requests for performance, context isn't necessarily passed up-front. This PR stems from a realization that a _function name_ isn't necessarily a binary decision (between context and no-context).

> You are still passing around magic strings of "Context" and "" in places. I personally am of the opinion that the current codebase is most clear.

 There is not much of a difference between `func_name $t "Context"` and `func_name $t ""` **vs.** `func_name_none $t` and `func_name_context $t`: We still pass context at some point (when it's wanted). However, the PR is more flexible as it allows us adjust the suffix — rather than having to edit `funcs.go.tpl` (and additionally the template) — when we deviate from the provided binary options. With the same reasoning, one could argue that the user should rely on `eval ( func_name $t + "string")`. However, this is more complicated.

Feel free to close the PR if it doesn't align with the project's purpose: Templating data access code made simple.

**Comment by kenshaw** [comment]
@switchupcb I really do appreciate the work / effort you've put into this, but I see this as a superficial change that doesn't accomplish much or anything. `xo` now has an extremely flexible way to change the Go functions used in the different templates via `funcs.go.tpl`. Much of the reason why I had exposed this functionality was so that individual projects could alter the templates on their own without much fuss. As such, please feel free to make these changes on your local project, and to use the modified/custom templates via the `--src`/`-d` command-line options. Again, appreciate the work/effort you put into this. Cheers.

**Pull request closed without merging**
