### PR TITLE
Support table_name prefix to the enum type name

### PR DESCRIPTION
**Pull request by zchee**
Support `table_name` prefix to the `enum` type name.

Sometimes `enum` type name conflicts with another `enum` name. So, add a new `--go-enum-table-prefix`  flag which prepends own `table_name` to `enum` prefix.
Also, add the `table` template function for backward compatibility because if change `field` template function directly, broken existing templates for xo users.

### CODE REVIEW

**Comment by kenshaw** [comment]
I'm fine with this functionality in principle. Once you've finished with this PR, can you please rebase into a single commit? I've read through the changes you've made so far, and everything seems to be fine, but I'll hold off verifying if it works properly until you've let me know the PR has been fully staged/completed.

**Comment by zchee** [comment]
@kenshaw Squashed, PTAL.

**Comment by zchee** [comment]
@kenshaw sorry, ping

**Comment by kenshaw** [comment]
@zchee I've merged this, but it breaks the examples, as well as changes the templates to have incorrect end lines. Would it be possible for you to fix this? Thanks.

**Comment by zchee** [comment]
Thanks for merged!
will do.

**Comment by kenshaw** [comment]
@zchee Please note that I was forced to revert these changes out, as it's broken for basically every PostgreSQL and MySQL query. I've branched it off to `broken`; if you'd like this feature back, please fix the issues on the `broken` branch, and submit a PR against that branch. I had spent some time to get the `broken` branch working, and it has @zhany 's PR on it, which fixes the PostgreSQL query.

**Comment by zchee** [comment]
@kenshaw ah, thanks!
@zhany you too 🙇‍♂️

**Pull request merged**
